<?xml version="1.0" encoding="utf-8"?><Database Name="Señales_Mioelectricas" Class="BaseDeDatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Señales_Mioelectricas;Integrated Security=True" SettingsObjectName="SeñalesMioelectricas.Properties.Settings" SettingsPropertyName="Señales_MioelectricasConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.documentos" Member="documentos">
    <Type Name="documentos">
      <Column Name="ID_Documento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre_Documento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre_Real" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Doc" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ID_Paciente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Paciente_documentos" Member="Paciente" ThisKey="ID_Paciente" OtherKey="ID_Paciente" Type="Paciente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Medico" Member="Medico">
    <Type Name="Medico">
      <Column Name="ID_Medico" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Apellido_Paterno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Apellido_Materno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Medico_Paciente" Member="Paciente" ThisKey="ID_Medico" OtherKey="ID_Medico" Type="Paciente" />
      <Association Name="Usuario_Medico" Member="Usuario" ThisKey="ID_User" OtherKey="ID_User" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Paciente" Member="Paciente">
    <Type Name="Paciente">
      <Column Name="ID_Paciente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Apellido_Paterno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Apellido_Materno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="ID_Medico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Paciente_documentos" Member="documentos" ThisKey="ID_Paciente" OtherKey="ID_Paciente" Type="documentos" />
      <Association Name="Medico_Paciente" Member="Medico" ThisKey="ID_Medico" OtherKey="ID_Medico" Type="Medico" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Member="Usuario1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Usuario_Medico" Member="Medico" ThisKey="ID_User" OtherKey="ID_User" Type="Medico" />
    </Type>
  </Table>
  <Table Name="dbo.ReporteV" Member="ReporteVs">
    <Type Name="ReporteV">
      <Column Name="ID_Paciente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Apellido_Paterno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Apellido_Materno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="ID_Medico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gestante" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Actividad_fisica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Diabetico" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Promedio_lectura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dolor_Percibido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medicamento" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>