//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeñalesMioelectricas
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos
    {
        public int ID_Documento { get; set; }
        public string Nombre_Documento { get; set; }
        public string Nombre_Real { get; set; }
        public byte[] Doc { get; set; }
        public Nullable<int> ID_Paciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
